server:
  port: 80

spring:
  application:
    name: KgcOA
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.8.106:8066/kgcoa?useUnicode=true&characterEncoding=utf-8&
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  # redis
  redis:
    password: 123456
    port: 6379
    host: 192.168.8.106
  # 缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true




# 文件保存的位置
file-save-path: X:/upload/


#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.example.entity
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


# 配置项目的日志级别, cn.kgc.springboot01包下的类日志级别是debug级别(debug->info->warn->error)
logging:
  level:
    com.example: debug



#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    auto-mapping-behavior: full
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: cn.kgc.springboot01.entity